Fix typos
thinkst/opencanary pull request #287
Opened 2023-08-02 21:08 UTC by stavares843

## Proposed changes

Fix typos across codebase.

## Types of changes

What types of changes does your code introduce to this repository?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update

2023-08-02 21:18 UTC, jayjb requested changes

2023-08-02 21:18 UTC, jayjb commented on docs/services/windows.rst
> -       browseable = yes
this is config setting.

2023-08-02 21:18 UTC, jayjb commented on opencanary/test/module_test.py
> +        # a 403 statutes code.
this should be `status`

2023-08-02 21:53 UTC, stavares843 commented on docs/services/windows.rst
> +       browsable = yes
```suggestion
       browseable = yes
```

2023-08-02 21:54 UTC, stavares843 commented on opencanary/test/module_test.py
> +        # a 403 statutes code.
```suggestion
        # a 403 status code.
```

2023-08-02 21:54 UTC, stavares843 commented on opencanary/test/module_test.py
> +        # a 403 statutes code.
updated 🔨

2023-08-02 21:54 UTC, stavares843 commented on docs/services/windows.rst
> -       browseable = yes
reverted 🔨

2023-08-03 07:45 UTC, jayjb approved these changes

2023-08-03 07:46 UTC, merged